name: Deploy UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-ui.yml"
      - ".github/workflows/deploy-ui-reusable.yml"
      - ".github/workflows/refresh-data.yml"
      - "ui/**"

jobs:
  deploy:
    uses: ./.github/workflows/deploy-ui-reusable.yml
    permissions:
      contents: read
      pages: write
      id-token: write
