name: Deploy UI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-ui.yml"
      - "config/tickers.json"
      - "data/**"
      - "ui/**"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-ui
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ui/package-lock.json
          node-version: 22

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install UI dependencies
        working-directory: ui
        run: npm ci

      - name: Build UI
        working-directory: ui
        env:
          BASE_PATH: /${{ github.event.repository.name }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ui/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
